/**
 * @file src/features/sportsLeague/data.js
 * @description Declares static seed metadata for sports league live text pages.
 */

export const SPORTS_LEAGUE_CATEGORY_ID = '2026-spring-grade3-boys-soccer';
export const SPORTS_LEAGUE_STORAGE_VERSION = '2026.03.15';
export const SPORTS_LEAGUE_MANAGER_ROLES = ['admin', 'student_council'];

export const SPORTS_EVENT_TEMPLATES = [
  {
    id: 'note',
    label: '일반',
    helper: '일반 운영 문구를 입력합니다.',
    placeholder: '예: 킥오프 직전 선수들이 입장했습니다.',
    defaultStatus: null,
  },
  {
    id: 'kickoff',
    label: '경기 시작',
    helper: '킥오프 직후 경기 시작 안내를 올립니다.',
    placeholder: '예: 휘슬과 함께 경기가 시작됐습니다.',
    defaultStatus: 'kickoff',
  },
  {
    id: 'goal',
    label: '득점',
    helper: '득점 직후 점수를 함께 기록합니다.',
    placeholder: '예: 3-6의 중거리 슛이 그대로 골문으로 들어갑니다!',
    defaultStatus: 'live',
  },
  {
    id: 'yellow',
    label: '경고',
    helper: '옐로카드 상황을 기록합니다.',
    placeholder: '예: 거친 태클로 경고가 선언됐습니다.',
    defaultStatus: 'live',
  },
  {
    id: 'red',
    label: '퇴장',
    helper: '레드카드 상황을 기록합니다.',
    placeholder: '예: 누적 경고로 퇴장이 선언됐습니다.',
    defaultStatus: 'live',
  },
  {
    id: 'halftime',
    label: '전반 종료',
    helper: '전반 종료 시점 안내',
    placeholder: '예: 전반이 종료됐습니다. 잠시 후 후반이 시작됩니다.',
    defaultStatus: 'halftime',
  },
  {
    id: 'second_half',
    label: '후반 시작',
    helper: '후반 시작 안내',
    placeholder: '예: 후반전이 시작됐습니다.',
    defaultStatus: 'live',
  },
  {
    id: 'fulltime',
    label: '경기 종료',
    helper: '최종 스코어를 함께 확정합니다.',
    placeholder: '예: 경기 종료! 결승행 팀이 결정됐습니다.',
    defaultStatus: 'completed',
  },
];

export const SPORTS_LEAGUE_SEED = {
  category: {
    id: SPORTS_LEAGUE_CATEGORY_ID,
    title: '2026 1학기 3학년 남자 축구',
    subtitle: '스포츠리그 반대항전 문자중계',
    seasonLabel: '2026 1학기',
    gradeLabel: '3학년',
    sportLabel: '남자 축구',
    statusNote: '실시간 문자중계 등록은 학생회와 관리자만 가능합니다.',
    scheduleWindowLabel: '2026.03.16 ~ 2026.04.08',
    matchTimeLabel: '12:45 킥오프 · 전후반 각 20분 · 1분 휴식',
    broadcastLabel: 'BroadcastChannel + localStorage 실시간 동기화 데모',
    locationLabel: '범서고등학교 스포츠리그',
  },
  teams: [
    { id: 'team-3-6', name: '3-6', shortName: '3-6', group: 'A', tone: 'groupA', displayOrder: 0 },
    { id: 'team-3-8', name: '3-8', shortName: '3-8', group: 'A', tone: 'groupA', displayOrder: 1 },
    { id: 'team-3-9', name: '3-9', shortName: '3-9', group: 'A', tone: 'groupA', displayOrder: 2 },
    { id: 'team-3-10', name: '3-10', shortName: '3-10', group: 'A', tone: 'groupA', displayOrder: 3 },
    { id: 'team-3-1-3-3', name: '3-1·3-3', shortName: '3-1·3-3', group: 'B', tone: 'groupB', displayOrder: 4 },
    { id: 'team-3-2-3-4', name: '3-2·3-4', shortName: '3-2·3-4', group: 'B', tone: 'groupB', displayOrder: 5 },
    { id: 'team-3-5-3-7', name: '3-5·3-7', shortName: '3-5·3-7', group: 'B', tone: 'groupB', displayOrder: 6 },
    { id: 'placeholder-a-1', name: 'A조 1위', shortName: 'A조 1위', group: 'K', tone: 'knockout', displayOrder: 7 },
    { id: 'placeholder-a-2', name: 'A조 2위', shortName: 'A조 2위', group: 'K', tone: 'knockout', displayOrder: 8 },
    { id: 'placeholder-b-1', name: 'B조 1위', shortName: 'B조 1위', group: 'K', tone: 'knockout', displayOrder: 9 },
    { id: 'placeholder-b-2', name: 'B조 2위', shortName: 'B조 2위', group: 'K', tone: 'knockout', displayOrder: 10 },
    {
      id: 'placeholder-semi-1-winner',
      name: '준결승1 승리',
      shortName: '준결승1 승리',
      group: 'K',
      tone: 'knockout',
      displayOrder: 11,
    },
    {
      id: 'placeholder-semi-2-winner',
      name: '준결승2 승리',
      shortName: '준결승2 승리',
      group: 'K',
      tone: 'knockout',
      displayOrder: 12,
    },
  ],
  matches: [
    {
      id: 'match-a-1',
      phase: 'group',
      stageLabel: 'A조 1차전',
      group: 'A',
      weekLabel: '1주차',
      kickoffAt: '2026-03-16T12:45:00+09:00',
      teamAId: 'team-3-6',
      teamBId: 'team-3-8',
      status: 'upcoming',
      score: { teamA: 0, teamB: 0 },
    },
    {
      id: 'match-a-2',
      phase: 'group',
      stageLabel: 'A조 2차전',
      group: 'A',
      weekLabel: '1주차',
      kickoffAt: '2026-03-18T12:45:00+09:00',
      teamAId: 'team-3-9',
      teamBId: 'team-3-10',
      status: 'upcoming',
      score: { teamA: 0, teamB: 0 },
    },
    {
      id: 'match-b-1',
      phase: 'group',
      stageLabel: 'B조 1차전',
      group: 'B',
      weekLabel: '1주차',
      kickoffAt: '2026-03-19T12:45:00+09:00',
      teamAId: 'team-3-1-3-3',
      teamBId: 'team-3-2-3-4',
      status: 'upcoming',
      score: { teamA: 0, teamB: 0 },
    },
    {
      id: 'match-a-3',
      phase: 'group',
      stageLabel: 'A조 3차전',
      group: 'A',
      weekLabel: '1주차',
      kickoffAt: '2026-03-20T12:45:00+09:00',
      teamAId: 'team-3-6',
      teamBId: 'team-3-9',
      status: 'upcoming',
      score: { teamA: 0, teamB: 0 },
    },
    {
      id: 'match-a-4',
      phase: 'group',
      stageLabel: 'A조 4차전',
      group: 'A',
      weekLabel: '2주차',
      kickoffAt: '2026-03-23T12:45:00+09:00',
      teamAId: 'team-3-8',
      teamBId: 'team-3-10',
      status: 'upcoming',
      score: { teamA: 0, teamB: 0 },
    },
    {
      id: 'match-b-2',
      phase: 'group',
      stageLabel: 'B조 2차전',
      group: 'B',
      weekLabel: '2주차',
      kickoffAt: '2026-03-25T12:45:00+09:00',
      teamAId: 'team-3-1-3-3',
      teamBId: 'team-3-5-3-7',
      status: 'upcoming',
      score: { teamA: 0, teamB: 0 },
    },
    {
      id: 'match-a-5',
      phase: 'group',
      stageLabel: 'A조 5차전',
      group: 'A',
      weekLabel: '3주차',
      kickoffAt: '2026-03-30T12:45:00+09:00',
      teamAId: 'team-3-6',
      teamBId: 'team-3-10',
      status: 'upcoming',
      score: { teamA: 0, teamB: 0 },
    },
    {
      id: 'match-a-6',
      phase: 'group',
      stageLabel: 'A조 6차전',
      group: 'A',
      weekLabel: '3주차',
      kickoffAt: '2026-04-01T12:45:00+09:00',
      teamAId: 'team-3-8',
      teamBId: 'team-3-9',
      status: 'upcoming',
      score: { teamA: 0, teamB: 0 },
    },
    {
      id: 'match-b-3',
      phase: 'group',
      stageLabel: 'B조 3차전',
      group: 'B',
      weekLabel: '3주차',
      kickoffAt: '2026-04-02T12:45:00+09:00',
      teamAId: 'team-3-2-3-4',
      teamBId: 'team-3-5-3-7',
      status: 'upcoming',
      score: { teamA: 0, teamB: 0 },
    },
    {
      id: 'match-semi-1',
      phase: 'knockout',
      stageLabel: '준결승 1차전',
      group: 'K',
      weekLabel: '3주차',
      kickoffAt: '2026-04-03T12:45:00+09:00',
      teamAId: 'placeholder-a-1',
      teamBId: 'placeholder-b-2',
      status: 'upcoming',
      score: { teamA: 0, teamB: 0 },
    },
    {
      id: 'match-semi-2',
      phase: 'knockout',
      stageLabel: '준결승 2차전',
      group: 'K',
      weekLabel: '4주차',
      kickoffAt: '2026-04-06T12:45:00+09:00',
      teamAId: 'placeholder-b-1',
      teamBId: 'placeholder-a-2',
      status: 'upcoming',
      score: { teamA: 0, teamB: 0 },
    },
    {
      id: 'match-final',
      phase: 'final',
      stageLabel: '결승전',
      group: 'K',
      weekLabel: '4주차',
      kickoffAt: '2026-04-08T12:45:00+09:00',
      teamAId: 'placeholder-semi-1-winner',
      teamBId: 'placeholder-semi-2-winner',
      status: 'upcoming',
      score: { teamA: 0, teamB: 0 },
    },
  ],
  rules: {
    format: [
      '8대8 경기로 진행됩니다.',
      '교체 횟수 제한은 없습니다.',
      '선수 집합은 12:42, 전반은 12:45~13:05, 후반은 13:06~13:26입니다.',
    ],
    points: ['승리 3점', '무승부 1점', '패배 0점'],
    ranking: ['득실차', '다득점', '맞대결 결과', '동전던지기'],
    notes: [
      '집합 시간 미준수로 인한 인원 부족은 그대로 진행되며 불이익은 반별 책임입니다.',
      '4강 토너먼트부터 무승부 시 청소시간 승부차기로 승패를 결정합니다.',
      '심판 판정 불응 또는 규칙 위반 시 반대항전이 중단될 수 있습니다.',
      '이번 반대항전부터 옐로카드와 레드카드가 도입됩니다.',
    ],
  },
  liveEvents: [],
  standingsOverrides: {
    A: null,
    B: null,
  },
  updatedAt: null,
  storageVersion: SPORTS_LEAGUE_STORAGE_VERSION,
};
