/**
 * @typedef {'spring' | 'fall'} AcademicSemester
 * @typedef {'ceremony' | 'exam' | 'holiday' | 'break' | 'studentLife' | 'trip' | 'college'} AcademicCategory
 *
 * @typedef AcademicCalendarEvent
 * @property {string} id
 * @property {string} title
 * @property {string} startDate
 * @property {string} endDate
 * @property {AcademicSemester} semester
 * @property {AcademicCategory} category
 * @property {string[]} audience
 * @property {string} [note]
 * @property {number} sourcePage
 *
 * @typedef AcademicSemesterMeta
 * @property {AcademicSemester} id
 * @property {string} label
 * @property {string} startDate
 * @property {string} endDate
 * @property {number} schoolDays
 * @property {string} breakSummary
 */

export const ACADEMIC_YEAR_META = {
  label: '2026학년도',
  startDate: '2026-03-01',
  endDate: '2027-02-28',
  semesters: /** @type {AcademicSemesterMeta[]} */ ([
    {
      id: 'spring',
      label: '1학기',
      startDate: '2026-03-01',
      endDate: '2026-07-31',
      schoolDays: 95,
      breakSummary: '7월 22일 ~ 8월 12일',
    },
    {
      id: 'fall',
      label: '2학기',
      startDate: '2026-08-01',
      endDate: '2027-02-28',
      schoolDays: 95,
      breakSummary: '12월 31일 ~ 1월 31일, 2월 5일 ~ 2월 28일',
    },
  ]),
  notes: [
    'PDF 원문 기준으로 구성했으며, 교육과정 운영에 따라 추후 변경될 수 있습니다.',
    '1학년 학부모 대상 입시 설명회: 2026년 4월 1일',
    '2~3학년 입시 설명회: 2026년 5월 21일 ~ 5월 22일',
    '7월 16일 전문직업인 특강(1, 2학년) 및 진로나눔장터(전학년) 운영',
  ],
};

export const ACADEMIC_CATEGORY_META = {
  ceremony: { label: '의식', tone: 'ceremony' },
  exam: { label: '시험', tone: 'exam' },
  holiday: { label: '휴일', tone: 'holiday' },
  break: { label: '방학', tone: 'break' },
  studentLife: { label: '학교행사', tone: 'studentLife' },
  trip: { label: '체험/여행', tone: 'trip' },
  college: { label: '진학', tone: 'college' },
};

/** @type {AcademicCalendarEvent[]} */
export const ACADEMIC_EVENTS = [
  {
    id: 'spring-substitute-holiday-0302',
    title: '대체공휴일',
    startDate: '2026-03-02',
    endDate: '2026-03-02',
    semester: 'spring',
    category: 'holiday',
    audience: ['all'],
    note: '삼일절 대체공휴일',
    sourcePage: 1,
  },
  {
    id: 'opening-ceremony-0303',
    title: '개학식',
    startDate: '2026-03-03',
    endDate: '2026-03-03',
    semester: 'spring',
    category: 'ceremony',
    audience: ['2', '3'],
    note: '2, 3학년',
    sourcePage: 1,
  },
  {
    id: 'entrance-ceremony-0304',
    title: '입학식',
    startDate: '2026-03-04',
    endDate: '2026-03-04',
    semester: 'spring',
    category: 'ceremony',
    audience: ['1'],
    note: '1학년',
    sourcePage: 1,
  },
  {
    id: 'student-council-retreat-0320',
    title: '학생회수련회',
    startDate: '2026-03-20',
    endDate: '2026-03-21',
    semester: 'spring',
    category: 'studentLife',
    audience: ['student-council'],
    sourcePage: 1,
  },
  {
    id: 'school-trip-grade2-0323',
    title: '수학여행',
    startDate: '2026-03-23',
    endDate: '2026-03-26',
    semester: 'spring',
    category: 'trip',
    audience: ['2'],
    note: '2학년',
    sourcePage: 1,
  },
  {
    id: 'national-mock-all-0324',
    title: '전국연합평가',
    startDate: '2026-03-24',
    endDate: '2026-03-24',
    semester: 'spring',
    category: 'exam',
    audience: ['1', '2', '3'],
    note: '1, 2, 3학년',
    sourcePage: 1,
  },
  {
    id: 'field-trip-grade13-0326',
    title: '현장체험학습',
    startDate: '2026-03-26',
    endDate: '2026-03-26',
    semester: 'spring',
    category: 'trip',
    audience: ['1', '3'],
    note: '1, 3학년',
    sourcePage: 1,
  },
  {
    id: 'school-anniversary-0327',
    title: '개교기념일',
    startDate: '2026-03-27',
    endDate: '2026-03-27',
    semester: 'spring',
    category: 'holiday',
    audience: ['all'],
    sourcePage: 1,
  },
  {
    id: 'admission-briefing-grade1-0401',
    title: '입시 설명회',
    startDate: '2026-04-01',
    endDate: '2026-04-01',
    semester: 'spring',
    category: 'college',
    audience: ['1', 'guardian'],
    note: '1학년 학부모 대상',
    sourcePage: 1,
  },
  {
    id: 'standardized-test-0406',
    title: '표준화검사',
    startDate: '2026-04-06',
    endDate: '2026-04-06',
    semester: 'spring',
    category: 'exam',
    audience: ['1', '2', '3'],
    note: '1, 2, 3학년 1교시',
    sourcePage: 1,
  },
  {
    id: 'math-science-day-0408',
    title: '수학과학의 날 행사',
    startDate: '2026-04-08',
    endDate: '2026-04-08',
    semester: 'spring',
    category: 'studentLife',
    audience: ['all'],
    sourcePage: 1,
  },
  {
    id: 'discretionary-holiday-0424',
    title: '재량휴업일',
    startDate: '2026-04-24',
    endDate: '2026-04-24',
    semester: 'spring',
    category: 'holiday',
    audience: ['all'],
    sourcePage: 1,
  },
  {
    id: 'midterm-spring-0427',
    title: '중간고사',
    startDate: '2026-04-27',
    endDate: '2026-04-30',
    semester: 'spring',
    category: 'exam',
    audience: ['all'],
    sourcePage: 1,
  },
  {
    id: 'labor-day-0501',
    title: '노동절',
    startDate: '2026-05-01',
    endDate: '2026-05-01',
    semester: 'spring',
    category: 'holiday',
    audience: ['all'],
    sourcePage: 1,
  },
  {
    id: 'childrens-day-0505',
    title: '어린이날',
    startDate: '2026-05-05',
    endDate: '2026-05-05',
    semester: 'spring',
    category: 'holiday',
    audience: ['all'],
    sourcePage: 1,
  },
  {
    id: 'national-mock-grade3-0507',
    title: '전국연합평가',
    startDate: '2026-05-07',
    endDate: '2026-05-07',
    semester: 'spring',
    category: 'exam',
    audience: ['3'],
    note: '3학년',
    sourcePage: 1,
  },
  {
    id: 'grade1-retreat-0511',
    title: '1학년 수련회',
    startDate: '2026-05-11',
    endDate: '2026-05-12',
    semester: 'spring',
    category: 'studentLife',
    audience: ['1'],
    sourcePage: 1,
  },
  {
    id: 'sports-day-0515',
    title: '교내체육한마당',
    startDate: '2026-05-15',
    endDate: '2026-05-15',
    semester: 'spring',
    category: 'studentLife',
    audience: ['all'],
    sourcePage: 1,
  },
  {
    id: 'admission-briefing-grade23-0521',
    title: '입시 설명회',
    startDate: '2026-05-21',
    endDate: '2026-05-22',
    semester: 'spring',
    category: 'college',
    audience: ['2', '3'],
    note: '2~3학년 대상',
    sourcePage: 1,
  },
  {
    id: 'buddha-birthday-substitute-0525',
    title: '대체공휴일',
    startDate: '2026-05-25',
    endDate: '2026-05-25',
    semester: 'spring',
    category: 'holiday',
    audience: ['all'],
    note: '부처님오신날 대체공휴일',
    sourcePage: 1,
  },
  {
    id: 'local-election-0603',
    title: '지방선거',
    startDate: '2026-06-03',
    endDate: '2026-06-03',
    semester: 'spring',
    category: 'holiday',
    audience: ['all'],
    sourcePage: 1,
  },
  {
    id: 'national-mock-grade12-0604',
    title: '전국연합평가',
    startDate: '2026-06-04',
    endDate: '2026-06-04',
    semester: 'spring',
    category: 'exam',
    audience: ['1', '2'],
    note: '1, 2학년',
    sourcePage: 1,
  },
  {
    id: 'csat-mock-grade3-0604',
    title: '대수능 모의평가',
    startDate: '2026-06-04',
    endDate: '2026-06-04',
    semester: 'spring',
    category: 'exam',
    audience: ['3'],
    note: '3학년',
    sourcePage: 1,
  },
  {
    id: 'final-spring-0702',
    title: '기말고사',
    startDate: '2026-07-02',
    endDate: '2026-07-07',
    semester: 'spring',
    category: 'exam',
    audience: ['all'],
    note: '7월 4일, 5일은 주말',
    sourcePage: 1,
  },
  {
    id: 'national-mock-grade3-0708',
    title: '전국연합평가',
    startDate: '2026-07-08',
    endDate: '2026-07-08',
    semester: 'spring',
    category: 'exam',
    audience: ['3'],
    note: '3학년',
    sourcePage: 1,
  },
  {
    id: 'career-fair-0716',
    title: '전문직업인 특강·진로나눔장터',
    startDate: '2026-07-16',
    endDate: '2026-07-16',
    semester: 'spring',
    category: 'studentLife',
    audience: ['all'],
    note: '1, 2학년 전문직업인 특강(2~3교시), 전학년 진로나눔장터(4~7교시)',
    sourcePage: 1,
  },
  {
    id: 'constitution-day-0717',
    title: '제헌절',
    startDate: '2026-07-17',
    endDate: '2026-07-17',
    semester: 'spring',
    category: 'holiday',
    audience: ['all'],
    note: 'PDF에 표기된 기념일',
    sourcePage: 1,
  },
  {
    id: 'summer-closing-0721',
    title: '방학식',
    startDate: '2026-07-21',
    endDate: '2026-07-21',
    semester: 'spring',
    category: 'ceremony',
    audience: ['all'],
    sourcePage: 1,
  },
  {
    id: 'summer-break-0722',
    title: '여름방학',
    startDate: '2026-07-22',
    endDate: '2026-08-12',
    semester: 'spring',
    category: 'break',
    audience: ['all'],
    sourcePage: 1,
  },
  {
    id: 'fall-opening-0813',
    title: '개학',
    startDate: '2026-08-13',
    endDate: '2026-08-13',
    semester: 'fall',
    category: 'ceremony',
    audience: ['all'],
    sourcePage: 2,
  },
  {
    id: 'liberation-substitute-0817',
    title: '대체공휴일',
    startDate: '2026-08-17',
    endDate: '2026-08-17',
    semester: 'fall',
    category: 'holiday',
    audience: ['all'],
    note: '광복절 대체공휴일',
    sourcePage: 2,
  },
  {
    id: 'national-mock-grade12-0902',
    title: '전국연합평가',
    startDate: '2026-09-02',
    endDate: '2026-09-02',
    semester: 'fall',
    category: 'exam',
    audience: ['1', '2'],
    note: '1, 2학년',
    sourcePage: 2,
  },
  {
    id: 'csat-mock-grade3-0902',
    title: '대수능 모의평가',
    startDate: '2026-09-02',
    endDate: '2026-09-02',
    semester: 'fall',
    category: 'exam',
    audience: ['3'],
    note: '3학년',
    sourcePage: 2,
  },
  {
    id: 'wednesday-schedule-0922',
    title: '수요일 수업',
    startDate: '2026-09-22',
    endDate: '2026-09-22',
    semester: 'fall',
    category: 'studentLife',
    audience: ['all'],
    sourcePage: 2,
  },
  {
    id: 'discretionary-holiday-0923',
    title: '재량휴업일',
    startDate: '2026-09-23',
    endDate: '2026-09-23',
    semester: 'fall',
    category: 'holiday',
    audience: ['all'],
    sourcePage: 2,
  },
  {
    id: 'chuseok-0924',
    title: '추석연휴',
    startDate: '2026-09-24',
    endDate: '2026-09-25',
    semester: 'fall',
    category: 'holiday',
    audience: ['all'],
    sourcePage: 2,
  },
  {
    id: 'foundation-substitute-1005',
    title: '대체공휴일',
    startDate: '2026-10-05',
    endDate: '2026-10-05',
    semester: 'fall',
    category: 'holiday',
    audience: ['all'],
    note: '개천절 대체공휴일',
    sourcePage: 2,
  },
  {
    id: 'hangul-day-1009',
    title: '한글날',
    startDate: '2026-10-09',
    endDate: '2026-10-09',
    semester: 'fall',
    category: 'holiday',
    audience: ['all'],
    sourcePage: 2,
  },
  {
    id: 'cpr-education-1012',
    title: '심폐소생술교육',
    startDate: '2026-10-12',
    endDate: '2026-10-12',
    semester: 'fall',
    category: 'studentLife',
    audience: ['all'],
    note: '일과변경',
    sourcePage: 2,
  },
  {
    id: 'national-mock-all-1013',
    title: '전국연합평가',
    startDate: '2026-10-13',
    endDate: '2026-10-13',
    semester: 'fall',
    category: 'exam',
    audience: ['1', '2', '3'],
    note: '1, 2, 3학년',
    sourcePage: 2,
  },
  {
    id: 'midterm-fall-1013',
    title: '중간고사',
    startDate: '2026-10-13',
    endDate: '2026-10-16',
    semester: 'fall',
    category: 'exam',
    audience: ['all'],
    sourcePage: 2,
  },
  {
    id: 'field-trip-grade12-1023',
    title: '현장체험학습',
    startDate: '2026-10-23',
    endDate: '2026-10-23',
    semester: 'fall',
    category: 'trip',
    audience: ['1', '2'],
    note: '1, 2학년',
    sourcePage: 2,
  },
  {
    id: 'csat-precall-1118',
    title: '수능예비소집',
    startDate: '2026-11-18',
    endDate: '2026-11-18',
    semester: 'fall',
    category: 'college',
    audience: ['3'],
    note: '3학년',
    sourcePage: 2,
  },
  {
    id: 'csat-1119',
    title: '대학수학능력시험',
    startDate: '2026-11-19',
    endDate: '2026-11-19',
    semester: 'fall',
    category: 'college',
    audience: ['3'],
    note: '3학년',
    sourcePage: 2,
  },
  {
    id: 'discretionary-holiday-1120',
    title: '재량휴업일',
    startDate: '2026-11-20',
    endDate: '2026-11-20',
    semester: 'fall',
    category: 'holiday',
    audience: ['all'],
    sourcePage: 2,
  },
  {
    id: 'final-fall-1214',
    title: '기말고사',
    startDate: '2026-12-14',
    endDate: '2026-12-16',
    semester: 'fall',
    category: 'exam',
    audience: ['all'],
    sourcePage: 2,
  },
  {
    id: 'field-trip-grade3-1217',
    title: '현장체험학습',
    startDate: '2026-12-17',
    endDate: '2026-12-17',
    semester: 'fall',
    category: 'trip',
    audience: ['3'],
    note: '3학년',
    sourcePage: 2,
  },
  {
    id: 'promotion-review-1221',
    title: '졸업·진급 사정회',
    startDate: '2026-12-21',
    endDate: '2026-12-21',
    semester: 'fall',
    category: 'studentLife',
    audience: ['all'],
    sourcePage: 2,
  },
  {
    id: 'christmas-1225',
    title: '성탄절',
    startDate: '2026-12-25',
    endDate: '2026-12-25',
    semester: 'fall',
    category: 'holiday',
    audience: ['all'],
    sourcePage: 2,
  },
  {
    id: 'student-council-election-1228',
    title: '학생회선거',
    startDate: '2026-12-28',
    endDate: '2026-12-28',
    semester: 'fall',
    category: 'studentLife',
    audience: ['all'],
    sourcePage: 2,
  },
  {
    id: 'festival-1229',
    title: '축제',
    startDate: '2026-12-29',
    endDate: '2026-12-29',
    semester: 'fall',
    category: 'studentLife',
    audience: ['all'],
    sourcePage: 2,
  },
  {
    id: 'winter-closing-1230',
    title: '방학식',
    startDate: '2026-12-30',
    endDate: '2026-12-30',
    semester: 'fall',
    category: 'ceremony',
    audience: ['all'],
    sourcePage: 2,
  },
  {
    id: 'winter-break-1231',
    title: '겨울방학',
    startDate: '2026-12-31',
    endDate: '2027-01-31',
    semester: 'fall',
    category: 'break',
    audience: ['all'],
    sourcePage: 2,
  },
  {
    id: 'spring-opening-0201',
    title: '개학식',
    startDate: '2027-02-01',
    endDate: '2027-02-01',
    semester: 'fall',
    category: 'ceremony',
    audience: ['all'],
    sourcePage: 2,
  },
  {
    id: 'friday-schedule-0202',
    title: '금요일 수업',
    startDate: '2027-02-02',
    endDate: '2027-02-02',
    semester: 'fall',
    category: 'studentLife',
    audience: ['all'],
    sourcePage: 2,
  },
  {
    id: 'graduation-0204',
    title: '졸업식',
    startDate: '2027-02-04',
    endDate: '2027-02-04',
    semester: 'fall',
    category: 'ceremony',
    audience: ['all'],
    sourcePage: 2,
  },
  {
    id: 'closing-0204',
    title: '종업식',
    startDate: '2027-02-04',
    endDate: '2027-02-04',
    semester: 'fall',
    category: 'ceremony',
    audience: ['all'],
    sourcePage: 2,
  },
  {
    id: 'spring-break-0205',
    title: '춘계방학',
    startDate: '2027-02-05',
    endDate: '2027-02-28',
    semester: 'fall',
    category: 'break',
    audience: ['all'],
    sourcePage: 2,
  },
];

